volumes:
  rate-limits-db-data:
services:
  limits-db:
    image: mongo:8.0-noble
    container_name: highload_limits_db
    ports: 
      - "5433:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - rate-limits-db-data:/data/db
      - ./database/mongo-init.bash:/mongo-init.bash
    networks: 
      - highload
    command:
      ["bash", "/mongo-init.bash"]
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'quit(rs.status().myState == 1 ? 0 : 1)'"]
      interval: 5s
      timeout: 3s
      retries: 5

  
  
  limits-writer:
    build:
      context: .
    container_name: highload_limits_writer
    platform: linux/amd64
    environment:
      DatabaseSettings__Uri: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@limits-db:27017"
      DatabaseSettings__Database: "rateLimiterDB"
    ports:
      - "5001:5001"
    networks: 
      - highload
    depends_on:
      limits-db: 
        condition: service_healthy
