services:
  rate-limits-db-service:
    image: mongodb/mongodb-community-server:7.0.24-rc0-ubi8
    ports: 
      - "5433:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - rate-limits-db-data:/data/db
  
  
  rate-limits-service:
    build:
      context: .
    platform: linux/amd64
    environment:
      MongoSettings__Uri: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rate-limits-db-service:27017"
      MongoSettings__Database: "rate_limits"
    ports:
      - "5003:5002"
      
volumes:
  rate-limits-db-data:
