services:
  user-db-service:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  user-db-migrations:
    image: flyway/flyway:10
    environment:
      FLYWAY_URL: jdbc:postgresql://user-db-service:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/migrations
      FLYWAY_CLEAN_DISABLED: false
    volumes:
      - ./Database/sql/migrations:/migrations:ro
    command: ${FLYWAY_MIGRATION_MODE:-migrate}
    depends_on:
      user-db-service:
        condition: service_healthy
      

  user-service:
    build:
      context: .
    platform: linux/amd64
    environment:
      ASPNETCORE_URLS: "http://+:5002"
    ports:
      - "5002:5002"
    depends_on:
      user-db-migrations:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  user-db-data:
