services:
  rate-limits-reader-service:
    build:
      context: .
    platform: linux/amd64
    environment:
      DatabaseSettings__Uri: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rate-limits-db-service:27017"
      DatabaseSettings__Database: "rateLimiterDB"
    ports:
      - "4999:5000"
